# Creeper2 config

CONFIG_NAME: under-devnet
PRESET_BASE: under-devnet

DEPOSIT_CHAIN_ID: 27882
DEPOSIT_NETWORK_ID: 27882

# Genesis
GENESIS_FORK_VERSION: 0x20000089

# Altair
ALTAIR_FORK_EPOCH: 2
ALTAIR_FORK_VERSION: 0x20000090

# Merge
BELLATRIX_FORK_EPOCH: 4
BELLATRIX_FORK_VERSION: 0x20000091
TERMINAL_TOTAL_DIFFICULTY: 498

# Capella
CAPELLA_FORK_EPOCH: 10
CAPELLA_FORK_VERSION: 0x20000092

# Time parameters
SECONDS_PER_SLOT: 12
SLOTS_PER_EPOCH: 32

# Deposit contract
DEPOSIT_CONTRACT_ADDRESS: 000000000000000000000000000000000000beef

# Make fast-track
MIN_PER_EPOCH_CHURN_LIMIT: 16
BAILOUT_SCORE_THRESHOLD: 675000000000000000
ETH1_FOLLOW_DISTANCE: 8
EPOCHS_PER_ETH1_VOTING_PERIOD: 2
MAX_SEED_LOOKAHEAD: 1
